name: Deploy CV Scanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Deploy UI (Static Web App)
      - name: Deploy UI
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_UI }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "UI/CV-Scanner"
          output_location: "build"

      # 3. Deploy API (App Service)
      - name: Deploy API
        uses: azure/webapps-deploy@v2
        with:
          app-name: cvscanner-api
          package: ./api

      # 4. Deploy Database Migrations (if any)
      - name: Run DB migrations
        run: |
          echo "Running DB migrations..."
          # Replace with your migration command, e.g.
          # dotnet ef database update
          # or flask db upgrade
