name: CV-Scanner Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Build, Test, Deploy API (Java 21)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate SQL Server exists in SQL RG
        run: |
          SERVER="${{ secrets.SQL_SERVER_NAME }}"
          RG="${{ secrets.SQL_RESOURCE_GROUP }}"
          if ! az sql server show -g "$RG" -n "$SERVER" >/dev/null 2>&1; then
            echo "ERROR: SQL server '$SERVER' not found in resource group '$RG'." >&2
            echo "Tip: Set secrets SQL_SERVER_NAME (logical server name, no domain) and SQL_RESOURCE_GROUP (e.g. CV_Scanner)." >&2
            az sql server list --query "[].{name:name, rg:resourceGroup}" -o table || true
            exit 1
          fi

      # Temporarily allow the GitHub runner IP to access Azure SQL (remove at end)
      - name: Open SQL firewall for runner IP
        id: sql_fw
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "ip=$IP" >> "$GITHUB_OUTPUT"
          az sql server firewall-rule create \
            -g "${{ secrets.SQL_RESOURCE_GROUP }}" \
            -s "${{ secrets.SQL_SERVER_NAME }}" \
            -n "gh-${GITHUB_RUN_ID}" \
            --start-ip-address "$IP" \
            --end-ip-address "$IP"

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          cache-dependency-path: API/api/pom.xml

      - name: Make mvnw executable
        run: chmod +x API/api/mvnw

      - name: Build & Test API against production DB
        working-directory: API/api
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          ./mvnw -B -ntp -DskipTests=false test
          ./mvnw -B -ntp -DskipTests package

      - name: Close SQL firewall rule
        if: always()
        run: |
          az sql server firewall-rule delete \
            -g "${{ secrets.SQL_RESOURCE_GROUP }}" \
            -s "${{ secrets.SQL_SERVER_NAME }}" \
            -n "gh-${GITHUB_RUN_ID}"

      - name: Locate API artifact
        id: api_artifact
        run: |
          JAR_PATH=$(ls -1 API/api/target/*.jar | grep -v '\.original$' | head -n 1)
          echo "jar=$JAR_PATH" >> "$GITHUB_OUTPUT"
          ls -lh "$JAR_PATH"

      - name: Deploy API (jar)
        run: |
          az webapp deploy \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-api" \
            --src-path "${{ steps.api_artifact.outputs.jar }}" \
            --type jar

      - name: Configure API app settings
        run: |
          az webapp config appsettings set \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-api" \
            --settings DB_URL='${{ secrets.DB_URL }}' DB_USER='${{ secrets.DB_USER }}' DB_PASS='${{ secrets.DB_PASS }}'
  ai:
    name: Deploy AI (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build AI package (prebuilt, slim)
        run: |
          set -euo pipefail
          rm -rf ai_build venv ai.zip
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r AI/requirements.txt -t ai_build
          python -c "import torch, sys; print('Torch OK', torch.__version__)"
