name: CV-Scanner Deployment

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy API to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cvscanner-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

  ai:
    name: Deploy AI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy AI to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cvscanner-ai"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

  ui:
    name: Deploy React UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: UI/CV-Scanner/package-lock.json

      - name: Install UI dependencies
        working-directory: UI/CV-Scanner
        run: npm ci || npm install --legacy-peer-deps

      - name: Build React UI
        working-directory: UI/CV-Scanner
        run: npm run build

      - name: Deploy React UI to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.UI_STATIC_WEBAPP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "UI/CV-Scanner"
          output_location: "dist"
          skip_app_build: true
