name: CV-Scanner Deployment

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Package API
        run: |
          API_PATH="API"
          test -d "$API_PATH" || (echo "API folder not found at $API_PATH" && exit 1)
          cd "$API_PATH"
          zip -r ../api.zip . -x "**/node_modules/**" "**/.git/**"
          cd -
          ls -lh api.zip

      - name: Deploy API (zip)
        run: |
          az webapp deploy \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-api" \
            --src-path "api.zip" \
            --type zip

  ai:
    name: Deploy AI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Package AI
        run: |
          AI_PATH="AI"
          test -d "$AI_PATH" || (echo "AI folder not found at $AI_PATH" && exit 1)
          cd "$AI_PATH"
          zip -r ../ai.zip . -x "**/node_modules/**" "**/.git/**"
          cd -
          ls -lh ai.zip

      - name: Deploy AI (zip)
        run: |
          az webapp deploy \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-ai" \
            --src-path "ai.zip" \
            --type zip

  ui:
    name: Deploy React UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: UI/CV-Scanner/package-lock.json

      - name: Install UI dependencies
        working-directory: UI/CV-Scanner
        run: npm ci || npm install --legacy-peer-deps

      - name: Build React UI
        working-directory: UI/CV-Scanner
        run: npm run build

      - name: Verify dist exists
        run: test -f "UI/CV-Scanner/dist/index.html" && echo "dist found" || (echo "dist missing" && exit 1)

      - name: Deploy React UI to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.UI_STATIC_WEBAPP_API_TOKEN }}
          action: "upload"
          app_location: "UI/CV-Scanner/dist"
          skip_app_build: true
