name: CI/CD

on:
  push:
    branches:
      - main
      - dev
      - API-3
      - UI-*
      - API-*
      - DB-*
  pull_request:
    branches:
      - main
      - dev
      - API-3

jobs:
  api:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/API-')
    name: Build & Deploy Java API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build API
        run: mvn -B -f API/api/pom.xml package

      - name: Run API tests
        run: mvn -f API/api/pom.xml test

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cvscanner-api'
          slot-name: 'production'
          package: API/

  ui:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/UI-')
    name: Build & Deploy React UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: UI/CV-Scanner
        run: npm ci --legacy-peer-deps

      - name: Build React UI
        working-directory: UI/CV-Scanner
        run: npx vite build

      - name: Deploy React UI to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_UI }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "UI/CV-Scanner"
          output_location: "UI/CV-Scanner/dist"

