name: CV-Scanner Deployment

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Build, Test, Deploy API (Java 21)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          cache-dependency-path: API/api/pom.xml

      - name: Make mvnw executable
        run: chmod +x API/api/mvnw

      - name: Build & Test API
        working-directory: API/api
        run: |
          ./mvnw -B -ntp -DskipTests=false test
          ./mvnw -B -ntp -DskipTests package

      - name: Locate API artifact
        id: api_artifact
        run: |
          JAR_PATH=$(ls -1 API/api/target/*.jar | grep -v '\.original$' | head -n 1)
          echo "jar=$JAR_PATH" >> "$GITHUB_OUTPUT"
          ls -lh "$JAR_PATH"

      - name: Deploy API (jar)
        run: |
          az webapp deploy \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-api" \
            --src-path "${{ steps.api_artifact.outputs.jar }}" \
            --type jar

  ai:
    name: Deploy AI (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: AI/requirements.txt

      - name: Install AI dependencies
        working-directory: AI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package AI
        run: |
          cd AI
          zip -r ../ai.zip . \
            -x "**/__pycache__/**" "**/.git/**" "**/.venv/**" "**/.python_packages/**" "**/*.pyc"
          cd -
          ls -lh ai.zip

      - name: Deploy AI (zip)
        run: |
          az webapp deploy \
            --resource-group "rg-cvscanner" \
            --name "cvscanner-ai" \
            --src-path "ai.zip" \
            --type zip

  ui:
    name: Deploy React UI (SWA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: UI/CV-Scanner/package-lock.json

      - name: Install UI dependencies
        working-directory: UI/CV-Scanner
        run: npm ci || npm install --legacy-peer-deps

      - name: Build React UI
        working-directory: UI/CV-Scanner
        env:
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }} # set to https://cvscanner-api-eaaudbdneafub4e3.southafricanorth-01.azurewebsites.net
        run: npm run build

      - name: Verify dist exists
        run: test -f "UI/CV-Scanner/dist/index.html" && echo "dist found" || (echo "dist missing" && exit 1)

      - name: Deploy React UI to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.UI_STATIC_WEBAPP_API_TOKEN }}
          action: "upload"
          app_location: "UI/CV-Scanner/dist"
          skip_app_build: true
