name: CI

on:
  push:
    branches: [ main, dev, API-3 ]
  pull_request:
    branches: [ main, dev, API-3 ]

jobs:
  api:
    name: Build API (Java/Maven)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('API/api/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B -f API/api/pom.xml package

      - name: Run tests
        run: mvn -f API/api/pom.xml test

  ai:
    name: Build AI (Python/FastAPI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('AI/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f AI/requirements.txt ]; then
            pip install -r AI/requirements.txt
          else
            pip install fastapi uvicorn pydantic pytest
          fi

      - name: Run AI tests (or import check)
        run: |
          if ls AI/test_*.py 1> /dev/null 2>&1 || [ -d AI/tests ]; then
            pytest AI -q
          else
            echo "No AI tests found. Running a quick import check."
            python - <<'PY'
            import sys, importlib.util, pathlib
            path = pathlib.Path('AI/app.py')
            if not path.exists():
                print('AI/app.py not found'); sys.exit(1)
            spec = importlib.util.spec_from_file_location("app", str(path))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)  # type: ignore
            assert hasattr(mod, "app"), "Expected 'app' FastAPI instance in AI/app.py"
            print("Import check passed: app found")
            PY
          fi

  ui:
    name: Build UI (Node/React)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: UI/CV-Scanner/package-lock.json

      - name: Install deps
        working-directory: UI/CV-Scanner
        run: npm ci

      - name: Build UI
        working-directory: UI/CV-Scanner
        run: npm run build --if-present

      - name: Test UI
        working-directory: UI/CV-Scanner
        run: npm test --if-present -- --watchAll=false